[build]
  command = "next build"
  publish = "out"

[functions]
  directory = ".netlify/functions"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 8888

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_ENV = "production"

[template.environment]
  NEXT_PUBLIC_ENV = "Set your public env variable here"
  NODE_ENV = "production" 